name: Terraform Plan

on:
  pull_request:

permissions:
  id-token: write      # Required for AWS OIDC auth
  contents: read       # Required to read repo files

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::539935451710:role/github_oidc
          aws-region: us-east-1
          role-session-name: GitHubActions-Terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
